---
- name: Install apache
  apt:
    name: apache2
- name: Add the web server to the student-files group
  user:
    name: www-data
    groups:
      - student-files
    append: yes
- name: Enable per-user folders in Apache
  apache2_module:
    name: userdir
  notify: Restart apache
- name: Configure per-user folders in Apache
  copy:
    src: userdir.conf
    dest: /etc/apache2/mods-available
  notify: Restart apache
- name: Create students' web folders
  file:
    path: /var/www/students/{{ item.name }}
    recurse: yes
    group: student-files
    state: directory
    mode: 0770
    owner: "{{ item.name }}"
  loop: "{{ students }}"
  notify: Restart apache
