---
students:
  - { name: anne, id: 111111 }
  - { name: bob, id: 222222 }
  - { name: carol, id: 333333 }
  - { name: david, id: 444444 }
  - { name: eleanor, id: 555555 }

# I've included two configurations for PHP, which I call "secure" and
# "simple". The secure configuration isolates students' code so that it can't
# messes with other students' stuff, but it also has more moving parts, so to
# speak. If something goes wrong and you're not in the mood to troubleshoot,
# switch to "simple" by changing the line below (then running the configuration
# script).
php_mode: secure
