---
# Users who are able to administer the system. This list should probably
# include the user you created when you installed the OS, but you could add
# more as well.
admins:
  - ericwolgie

# The students who need access to the system. Their password will be their
# student ID, followed by an exclamation point.
students:
  - { name: anne, id: 111111 }
  - { name: bob, id: 222222 }
  - { name: carol, id: 333333 }
  - { name: david, id: 444444 }
  - { name: eleanor, id: 555555 }

# I've included two configurations for PHP, which I call "secure" and
# "simple". The secure configuration isolates students' code so that it can't
# messes with other students' stuff, but it also has more moving parts, so to
# speak. If something goes wrong and you're not in the mood to troubleshoot,
# switch to "simple" by changing the line below (then running the configuration
# script).
php_mode: secure
